---
- name: "Uninstall full postgres install components"
  block:
    - name: "Stop/Disable systemd service"
      systemd:
        name: postgresql-{{ postgres_major_version }}.service
        state: stopped
        enabled: false
      ignore_errors: true

    - name: "Remove postgres files"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/systemd/system/postgresq*.service
        - /usr/lib/systemd/system/postgresq*.service
        - "{{ postgres_basedir }}"

    - name: "Remove python-psycopg2 RPM"
      yum:
        name: python-psycopg2
        state: absent

  when: not postgres_rpm_only_install|bool

- name: "Uninstall postgres and RPMs"
  yum:
    name: "{{ postgres_rpms }}"
    state: absent
