---

# Redis uses a mix of sha1 and sha256 checksums.
# Determine the type of checksum based on its length and prefix the variable appropriately
- name: set redis checksum
  set_fact:
    redis_checksum: "{{ 'sha1' if redis_checksums[redis_version]|length == 40 else 'sha256' }}:{{ redis_checksums[redis_version] }}"
  when:
    - redis_verify_checksum|bool
    - redis_checksum is not defined
    - redis_version in redis_checksums

- name: check for existing source files
  stat:
    path: "/usr/local/src/redis-{{ redis_version }}"
  register: redis_src_dir

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: download_dir
  when: not redis_src_dir.stat.exists

- name: download redis
  get_url:
    url: "{{ artifactory_redis_url }}"
    dest: "{{ download_dir.path }}/{{ redis_version }}.tar.gz"
    checksum: "{{ redis_checksum|default(omit) }}"
    headers:
      X-JFrog-Art-Api: "{{ artifactory_token }}"
  register: redis_artifactory
  retries: 5
  delay: 15
  until: redis_artifactory is succeeded
  when:
    - not redis_tarball
    - not redis_src_dir.stat.exists

- name: upload redis
  copy:
    src: "{{ redis_tarball }}"
    dest: "{{ download_dir.path }}/{{ redis_version }}.tar.gz"
  when:
    - redis_tarball|default(false)
    - not redis_src_dir.stat.exists

- name: extract redis tarball
  unarchive:
    src: "{{ download_dir.path }}/{{ redis_version }}.tar.gz"
    dest: /usr/local/src
    creates: /usr/local/src/redis-{{ redis_version }}/Makefile
    copy: no
  when:
    - not ansible_check_mode
    - not redis_src_dir.stat.exists
